oauth2:
  client:
    registration:
      kakao:
        client-id: ${KAKAO_CLIENT_ID}
        client-secret: ${KAKAO_CLIENT_SECRET}
        token-uri: ${KAKAO_TOKEN_URI}
        user-info-uri: ${KAKAO_USER_INFO_URI}
      google:
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}
        token-uri: ${GOOGLE_TOKEN_URI}
        user-info-uri: ${GOOGLE_USER_INFO_URI}